### ISSUE TITLE
Adding complex mesh

### ISSUE THREAD

**Issue by jaysonl23** [liggiorgio/ar-collaborative#2]
So I tried to add a robot 3d model to the sharepreferenceprefabs , the 3d model was converted to prefab with the necessary components. such as colliders, rigid body, identity and destroy on fall. Am I missing something? because I can spawn it but I can't detect it like I can't move, rotate, or grab the robot, it seems it is not detected in the ray cast, or the system only supports regular polygons or do I need to make it a primitive collider or a mesh collider to be able to be collided with the raycast?

**Comment by liggiorgio** [comment]
Does your Prefab have an [ARC Entity](https://github.com/liggiorgio/ar-collaborative/wiki/ARC-Entity) Component?

This Component is in charge of synchronising GameObjects (spawned via [`ARCSession.Spawn()`](https://github.com/liggiorgio/ar-collaborative/wiki/ARC-Session-(Script-Reference)#public-methods)). It also lets you define many useful properties, one of which is **Is Interactable**. When enabled, it tells the ARC subsystem that GameObject can be manipulated by users, and will synchronise its position and rotation to other users in real-time. It MUST be assigned at the root-transform level of your GameObject. Therefore the proxy Collider you want to use for raycasting should be assigned to the root of your object, as currently returning the root from a raycast against children isn't supported.

---

You can raycast the GameObject via [`ARCSession.RaycastEntity()`](https://github.com/liggiorgio/ar-collaborative/wiki/ARC-Session-(Script-Reference)#public-methods), which accepts local-space transform data, with custom arguments. You can get that local data by querying the `ARCUser` Component:

    ARCUser user = GetComponent<ARCUser>();    //or get it somehow else

    int layer = 1 << 3;    //dedicated layer for special GameObjects detection (e.g. grab)
    ARCEntity entity = ARCSession.RaycastEntity(user.localCameraPosition, user.localCameraForward, 3f, layer);

    if (entity != null)
    {
        entity.Grab(user, position, rotation);
    }

Releasing entities isn't done automatically, so you should check for that case as well. Then, the code above becomes:

    ARCUser user = GetComponent<ARCUser>();    //or get it somehow else

    if (user.interactingEntity != null)
    {
        user.interactingEntity.Release(user, position, rotation);
    }
    else
    {
        int layer = 1 << 3;    //dedicated layer for special GameObjects detection (e.g. grab)
        ARCEntity entity = ARCSession.RaycastEntity(user.localCameraPosition, user.localCameraForward, 3f, layer);

        if (entity != null)
        {
            entity.Grab(user, position, rotation);
        }
    }

And don't forget `ARCSession.RaycastEntity()` is a server-only function, so we must execute the above code on user request on the server. We do that by defining a [`Command`](https://docs.unity3d.com/530/Documentation/ScriptReference/Networking.CommandAttribute.html):

    void MoveEntity()
    {
        CmdMoveEntity(user.localCameraPosition, user.localCameraRotation);
    }

    [Command]
    void CmdMoveEntity(Vector3 position, Quaternion rotation)
    {
        if (user.interactingEntity != null)
        {
            user.interactingEntity.Release(user, position, rotation);
        }
        else
        {
            int layer = 1 << 3;
            ARCEntity entity = ARCSession.RaycastEntity(position, rotation * Vector3.forward, 3f, layer);
            if (entity != null)
                entity.Grab(user, position, rotation);
        }
    }

The above code is the same as the [`UserInteractions.cs`](https://github.com/liggiorgio/ar-collaborative/blob/master/Assets/Examples/ARCSandbox/Scripts/UserInteraction.cs) script from the [ARC Sandbox](https://github.com/liggiorgio/ar-collaborative/tree/master/Assets/Examples/ARCSandbox) sample.

**Comment by jaysonl23** [comment]
yes thank youu. got this workout, it turns out that the prefab should have the same layer as to the others to make it work

**Comment by jaysonl23** [comment]
Sir Good day, I've tried a little thing to make it spice I tried to add a button to swap out the 3d models during runtime. For example the two devices are connected and spawing objects. Then I dedicated a special button which will change the last object in the arsessionsharef prefabs, after clicking that button the Object was swapped out in my end but in the other end the object is not appearing as I spawn it.

**Comment by jaysonl23** [comment]
to clear it out this is the scenario. I added a button in the arc sandbox sample. this button is dedicated to swapping the physics sphere with a robot prefab in runtime. After I clicked the button it was swapped out, because as I selected it in the drop-down and spawning it, it appears in my end. The problem is the other device could not see it. the other device could only see all the prefabs except the swapped out prefab. Could this be about the network?

**Comment by liggiorgio** [comment]
The feature you described can be implemented by nesting multiple 3D models under the same parent, and managing what model to display via a networked variable. So the problem here is just about network programming, not an issue related to ARC.
